# Use an official Python runtime as a parent image
FROM python:3.9.17-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Setup ENV variables
ENV USER_POSTGRES='postgres' \
    PASSWORD_POSTGRES='postgrespw' \
    COLUMN_NAMES="code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result" \
    DUMMIES_COL_NAMES="gender_1,gender_2,gender_3,gender_0,disability_1,disability_2,disability_0,age_band_1,age_band_2,age_band_3,age_band_0,highest_education_1,highest_education_2,highest_education_3,highest_education_4,highest_education_5,highest_education_0,imd_band_1,imd_band_2,imd_band_3,imd_band_4,imd_band_5,imd_band_6,imd_band_7,imd_band_8,imd_band_9,imd_band_10,imd_band_0,code_presentation_1,code_presentation_2,code_presentation_3,code_presentation_4,code_presentation_0,code_module_1,code_module_2,code_module_3,code_module_4,code_module_5,code_module_6,code_module_7,code_module_0,region_1,region_2,region_3,region_4,region_15,region_6,region_7,region_8,region_9,region_10,region_11,region_12,region_13,region_14,region_0" \
    CATEGORICAL_COLUMN_NAMES="code_module,code_presentation,gender,region,highest_education,imd_band,age_band,disability" \
    SECRET_KEY="34395748a9a33f1de1ffd8fcacc8cbcd41e21f6d8c083687" \
    DB_NAME="is_db_prototype" \
    MODEL_FOLDER_PATH="/Models"


RUN apt-get -q -y update

# Install libpq-dev (necessario para o psycopg2 aparentemente) e tk (aparentemente nao vem com a imagem do python)
RUN apt-get install -y libpq-dev
RUN apt-get install -y tk

# Upgrade pip
RUN pip install --upgrade pip
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]